services:
  minecraft-server:
    container_name: minecraft
    image: itzg/minecraft-server:java11
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: FORGE
      VERSION: 1.16.5
      FORGE_VERSION: "36.2.34"
      MEMORY: 12G
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data
