services:
  minecraft-server:
    container_name: minecraft
    image: itzg/minecraft-server:java21
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      VERSION: 1.20.1
      MEMORY: 12G
      TYPE: FORGE
      MODS_FILE: /extras/mods.txt
      REMOVE_OLD_MODS: "TRUE"
      OVERRIDE_ICON: "TRUE"
    env_file:
      - .env.server.properties
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data
      - ./extras:/extras
