services:
  minecraft-server:
    container_name: minecraft
    image: itzg/minecraft-server:java21
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    deploy:
    resources:
      limits:
        memory: 7G
    environment:
      EULA: "TRUE"
      VERSION: 1.20.1
      INIT_MEMORY: 2G
      MAX_MEMORY: 6500M
      TYPE: FORGE
      MODS_FILE: /extras/mods.txt
      REMOVE_OLD_MODS: "TRUE"
      OVERRIDE_ICON: "TRUE"
      ## Server properties
      MOTD: \u00A7kI\u00A7kI\u00A7kI\u00A71IC2018 \u00A74Minecraft \u00A76modded \u00A7aserver\u00A7kI\u00A7kI\u00A7kI
      ICON: /extras/logo.png
      DIFFICULTY: easy
      SPAWN_PROTECTION: 0
      ONLINE_MODE: false
      ALLOW_FLIGHT: true
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data
      - ./extras:/extras
